USE [master]
GO

/****** Object:  Database [Orange]    Script Date: 09/03/2021 11:39:23 ******/
CREATE DATABASE [Orange]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Orange', FILENAME = N'D:\Cursos\SQL Server\ORG20210308\DISCOS\SSD\Orange.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [G1] 
( NAME = N'F1', FILENAME = N'D:\Cursos\SQL Server\ORG20210308\DISCOS\C\F1.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ),
( NAME = N'F2', FILENAME = N'D:\Cursos\SQL Server\ORG20210308\DISCOS\C\F2.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [G2] 
( NAME = N'F3', FILENAME = N'D:\Cursos\SQL Server\ORG20210308\DISCOS\D\F3.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [G3] 
( NAME = N'F4', FILENAME = N'D:\Cursos\SQL Server\ORG20210308\DISCOS\E\F4.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB ), 
 FILEGROUP [HISTORICO] 
( NAME = N'F5', FILENAME = N'D:\Cursos\SQL Server\ORG20210308\DISCOS\F\F5.ndf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Orange_log', FILENAME = N'D:\Cursos\SQL Server\ORG20210308\DISCOS\SSD\Orange_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Orange].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Orange] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Orange] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Orange] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Orange] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Orange] SET ARITHABORT OFF 
GO

ALTER DATABASE [Orange] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Orange] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Orange] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Orange] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Orange] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Orange] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Orange] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Orange] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Orange] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Orange] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Orange] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Orange] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Orange] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Orange] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Orange] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Orange] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Orange] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Orange] SET RECOVERY FULL 
GO

ALTER DATABASE [Orange] SET  MULTI_USER 
GO

ALTER DATABASE [Orange] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Orange] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Orange] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Orange] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Orange] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Orange] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Orange] SET  READ_WRITE 
GO


-- Step 1. Create a partition function
CREATE PARTITION FUNCTION PorAño(int)
AS
	RANGE LEFT FOR VALUES (2021, 2022)
	RANGE LEFT FOR VALUES (2021)

v <= 2021  Historico
2021 < v <= 2022 Actual
2022 < v Futuro


GO
CREATE PARTITION FUNCTION PorMes(int)
AS
	RANGE RIGHT FOR VALUES (1,2,3,4,5,6,7,8,9,10,11,12)
GO

-- Step 2. Create a partition scheme that references the function
CREATE PARTITION SCHEME PaticionPorAño
AS 
	PARTITION PorAño 
	TO (G1, G2, G3)
GO
CREATE PARTITION SCHEME PaticionPorMes
AS 
	PARTITION PorMes 
	TO (G1,G1,G1,G1,G2,G2,G2,G2,G3,G3,G3,G3,G3)
GO


CREATE TABLE [dbo].[Llamada2](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[fecha] [date] NULL,
	[año] [int] NULL,
	[coste] [smallmoney] NOT NULL
)   ON PaticionPorMes(datepart(month, fecha)) 
GO
